### vars
@cookie = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjkzMzczMzg4ODMiLCJpYXQiOjE3MjkwNDg5OTksImV4cCI6MTcyOTEzNTM5OX0.XICZNhj5t-Ll-VUTTLDZMLepoEdQpyTL8pzXQ-IMB8o; Max-Age=86400; Path=/; Expires=Thu, 17 Oct 2024 03:23:19 GMT

### signup
POST http://localhost:3000/auth/signup 
Content-Type: application/json

{
    "name" : "amitanshu", 
    "email" : "amitanshu@gamil",
    "phone" : "9337338883",
    "password" : "12345678"

}

### login
POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "name" : "amitanshu", 
    "email" : "amitanshu@gamil",
    "phone" : "9337338883",
    "password" : "12345678"

}